### ISSUE TITLE
Explicit "repos" field appears flaky in teams.json 

### ISSUE THREAD

**Issue by bcoe** [googleapis/sloth#1073]
In `teams.json`, there is an explicit `repos` field which allows a team to indicate repositories that they are tracking work on.

The repository GoogleCloudPlatform/cloud-sql-go-connector has been added to this field, however this repository is not be appropriately tracked by SLOs.

**Comment by kurtisvg** [comment]
Additional datapoint: the [Cloud SQL proxy](https://github.com/GoogleCloudPlatform/cloudsql-proxy) repo has been in there for a while and is working fine, even without the "api: cloudsql" label.
