### ISSUE TITLE
Run `sloth tag-issues` as a kokoro job

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/sloth#141]
As of today sloth runs on my personal k8s cluster, using a personal access token provisioned from my account.  This is bad for so many reasons that I don't even have to list them 😆 

I would like to make the running of `sloth tag-issues` an automated task that uses the `yoshi-automation` account.  To set this up, we need:
- An environment where nodejs 10 is installed (the node:10-alpine docker image is great)
- The `SLOTH_GITHUB_TOKEN` environment variable must be set to a valid GitHub token
- Run the command `npx https://github.com/googleapis/sloth tag-issues` 
- Do that every 3 minutes :)

Please do let me know if you have any concerns or questions!

**Comment by JustinBeckwith** [comment]
cc @theacodes

**Comment by theacodes** [comment]
@busunkim96 please set this up using the `yoshi-automation` github account.

Thanks. :)
