### ISSUE TITLE
Missing info in README: necessary GitHub scopes

### ISSUE THREAD

**Issue by timburks** [googleapis/sloth#279]
From the **Usage** section: "You need to go create a personal access token in GitHub". 

Which scopes are needed for this?

**Comment by JustinBeckwith** [comment]
It depends on what you need to do.  If you're just trying to do issue querying, you may not need a token, or at least with any rights at all.  If you want to do things like `sloth labels` or `sloth users`  (which I generally do), you are gonna need the `admin:org` read & write access.  

The plan is to lift most of that functionality into a bot when our bot framework lands (coming to a yoshisaur near you in Q3)

**Comment by JustinBeckwith** [comment]
This is moving to a mostly private tool, so closing this out.
