### ISSUE TITLE
Create contractor sub team and reduce team membership duplication

### ISSUE THREAD

**Issue by crwilcox** [googleapis/sloth#290]
# Proposal
Reduce number of duplicate entries of individuals across teams to make managing permissions more straightforward

- Reduce Yoshi direct membership to a minimum number of people. Rely on sub teams to manage this
- All repositories contain the `yoshi` team, so having all people in each language team is redundant
- Create `yoshi-contractors` to migrate contractor team members off of parent `yoshi` team.
- Remove contractors from individual language teams. The rights given via yoshi are sufficient.
- Give Yoshi team write access to all repositories (some currently have read)
- Enable master branch protection on all repositories
- Create `CODEOWNERS` files for all repositories

**Comment by sduskis** [comment]
Don't we need to give contractors access by language?

**Comment by crwilcox** [comment]
as the permissions are currently configured, the yoshi group is trumping the others anyway. Really, all those other groups are giving is a list you can tag for PR review. So, we could keep doing this but it doesn't seem we use them that much. We could keep doing that, but even then, I might suggest we maintain them as separate groups to avoid duplication, `yoshi-cpp-contractors`

There is even a thought that those language groups don't make that much sense anymore as after the reorganization there is a bit more jumping around the different languages and really the real model is to have codeowners for specific areas unrelated to repository permissions.

**Comment by crwilcox** [comment]
Expanded proposal above to include thoughts on codeowners and master branch protection

**Comment by JustinBeckwith** [comment]
Much better!  Can we put numbers on the steps though?  I think some of these need to happen before others.

**Comment by JustinBeckwith** [comment]
We have a broader effort to cover this stuff in the internal doc.  Closing this out for now!
